# Kubernetes manifests are used to create, modify and delete Kubernetes resources such as pods, deployments, services or ingresses.
# It is a recommended practice to put resources related to the same microservice or application tier into the same file, and to group all of the files associated with your application in the same directory

apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: pub
spec:
  replicas: 1 # Run one pod matching the template
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
        tier: backend
    spec:
      containers:
      - name: publisher
        image: publisher:1.0.0
        ports: 
        - containerPort: 6895
      - name: subscriber  
        image: subscriber:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app: pub
  ports:
    - port: 6895
      nodePort: 30007